import { Injectable } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { CustomerService } from '../customers/customer.service';
import { Observable } from 'rxjs';

@Injectable()
export class Globals {
  postSet: string[] = [
    'Mudachikadu',
    'Nadiyam',
    'Sethubhavachatram',
    'Udayanadu',
    'Marungapallam',
    'Rudrachinthamani',
    'Kuruvikarambai',
    'Peravurani',
    'Manakadu',
    'Athani',
    'Pookkollai',
    'Karuppamanai',
    'Veeraiyankottai',
    'Perumagalur',
  ];
  nameSet: string[] = [
    'Kumaravel',
    'Moorthy',
    'Singalaxmi',
    'Mangayarkarasi',
    'Viswanathan',
    'Sellaiya',
    'Sekaran',
    'Peramaiyan',
    'Veerachamy',
    'Neelakandan',
    'Pandian',
    'Selvam',
    'Suba',
    'Samaiyan',
    'Laxmi',
    'Vadivel',
    'Sumathi',
    'Kavitha',
    'Sasikala',
    'Murugesan',
    'Madhiyalagan',
    'Ramachandran',
    'Chitra',
    'Jeganathan',
    'Suresh',
    'Kasthuri',
    'Yogamani',
    'Neelapriya',
    'Rajani',
    'Gnanam',
    'Kannagi',
    'Rani',
    'Selladurai',
    'Singaravelu',
    'Sureshkumar',
    'Anandhi',
    'Akilan',
    'Rathi',
    'Nathiya',
    'Sugumar',
    'Farooq',
    'Latha',
    'James',
    'Gunalan',
    'Gopi',
    'Banu',
    'Neela',
    'Ramanathan',
    'Ayyathurai',
    'Sulochana',
    'Senthilnathan',
    'Gnanaprakasam',
    'Mugundhan',
    'Gunasekar',
    'Vijayakumari',
    'Rajendran',
    'Parvathi',
    'Sinduja',
    'Subramanian',
    'Jegadeesan',
    'Kaliyammal',
    'Poongothai',
    'Saravanan',
    'Surendar',
    'Karuppaiyan',
    'Nithishkumar',
    'Dhanalaxmi',
    'Aravind',
    'Nandakumar',
    'Balasubramaniam',
    'Ramesh',
    'Allapichai',
    'Haji alima',
    'Dhanapriya',
    'Arumugam',
    'Sathish',
    'Saroja',
    'Pichaiyan',
    'Subbaiyan',
    'Veluchamy',
    'Perumal',
    'Chandrasekar',
    'Kunju',
    'Naguran',
    'Thangavel',
    'Kuttiambalam',
    'Arasu',
    'Kasinathan',
    'Veeraiya',
    'Vaidhiyalingam',
    'Murugan',
    'Vairavan',
    'Karuppaiya',
    'Palanivel',
    'Kailasam',
    'Dange',
    'Kasiyappan',
    'Pandi',
    'Sethurajan',
    'M.K.Pannerselvam',
    'Soundararajan',
    'Velmurugan',
    'Nagan',
    'Muthukaruppan',
    'Palraj',
    'Vasudevan',
    'Kumar',
    'Karthikeyan',
    'Mohamed maideen',
    'Anthonyraj',
    'Ussain',
    'Raja',
    'Kurthan',
    'Sellaiyan',
    'Muniyasamy',
    'Shanmugam',
    'Subramani',
    'Samikannu',
    'Sakthivel',
    'Chinnathambi',
    'Muthaiya',
    'Vijay',
    'Chandran',
    'Ayyappan',
    'Subbaiya',
    'Ganesan',
    'Murugaiyan',
    'Duraiarasan',
    'Solaimalai',
    'Jeyshankar',
    'Veerasamy',
    'Jinna',
    'Bharagathali',
    'Devendran',
    'Kalimuthu',
    'Sankar',
    'Anandhan',
  ];
  itemSet: string[] = [
    'Necklace',
    'Modhiram',
    'Mattal',
    'Thodu thongal',
    'Kasu',
    'Jimikki',
    'Thodu',
    'Kasu malai',
    'Kal thodu',
    'Ring',
    'Valayal',
    'Kai chain',
    'Dollar chain',
    'Kal modhiram',
    'Chain',
    'Chain (paludhu)',
    'Kal thodu jimikki',
    'Modhiram (paludhu)',
    'Thodu jimikki',
    'KPS Modhiram (nool)',
    'Meen dollar chain',
    'Chain (kokki paludhu)',
    'Mattal (1 kal illai paludhu)',
    'Necklace (paludhu)',
    'Mani',
    'Pottu',
    'Ma kasu',
    'Meen dollar',
    'Baby valayal',
    'Mani (nool)',
    'Thayathu',
    'Kal thodu thongal (paludhu)',
    'Dollar',
    'Modhiram (nool)',
    'Mattal (paludhu)',
    'Chain (kokki illai)',
    'Thodu (paludhu)',
    'Kai thodu jimikki',
    'Om dollar chain',
    'Thali kasu',
    'Yanai mudi ring',
  ];
}
